### ISSUE TITLE
[feat] 엔티티 구현

### ISSUE THREAD

**Issue by wldks1008** [34th-SOPKATHON-iOS-TEAM1/Server#1]
## 📌  Feature Issue
Todo, NotTodo, goal 엔티티 구현

## 📝  To-do

- [x] 투두 엔티티 구현
- [x] 낫투두 엔티티 구현
- [x] 목표 엔티티 구현
